### ISSUE TITLE
Rapid changes to query parameters are lost

### ISSUE THREAD

**Issue by trevorr** [amannn/next-query-params#21] opened 2022-10-19 23:13 UTC
**Describe the bug**

Setting multiple query parameters in quick succession (e.g. a single callback) causes only the last parameter to be reflected in the URL. Each parameter change overwrites the previous one, which is visible as a rapidly changing browser URL. This is because, unlike other router adapters, Next routing is asynchronous. (I'm using Next 12.3.1, in case that matters.)

**To Reproduce**

[I have no idea how to easily set up a CodeSandbox for this. If you have a starter one, I'm happy to modify it.]

Create some hooks:

```ts
const [near, setNear] = useQueryParam("near", StringParam);
const [lat, setLat] = useQueryParam("lat", NumberParam);
const [lon, setLon] = useQueryParam("lon", NumberParam);
const [radius, setRadius] = useQueryParam("radius", NumberParam);
```

Modify them all at once:

```ts
setNear("Some place", "replaceIn");
setLat(45, "replaceIn");
setLon(45, "replaceIn");
setRadius(1000, "replaceIn");
```

Only `?radius=1000` will end up in the URL.

**Expected behavior**

All of the query parameters should have been added: `?near=Some+place&lat=45&lon=45&radius=1000`.

**Draft fix**

I'm currently using the forked version below, which seems to work. Let me know if you'd accept a pull request. It does have a few other tweaks to make the linter happy in my project (e.g. no use of `as`).

```ts
import { useRouter } from "next/router";
import React from "react";
import { PartialLocation, QueryParamAdapter } from "use-query-params";

const pathnameRegex = /[^?#]+/u;

type Props = {
  shallow?: boolean;
  children(adapter: QueryParamAdapter): React.ReactElement | null;
};

type PartialLocationWithHash = PartialLocation & { hash?: string };

function NextQueryParamAdapter({ children, shallow = true }: Props) {
  const router = useRouter();
  const match = router.asPath.match(pathnameRegex);
  const pathname = match ? match[0] : router.asPath;

  const location = React.useRef(getLocation(router.asPath, router.isReady));
  React.useEffect(() => {
    location.current = getLocation(router.asPath, router.isReady);
  }, [router.asPath, router.isReady]);

  const timeoutId = React.useRef<ReturnType<typeof setTimeout>>();

  const adapter: QueryParamAdapter = React.useMemo(() => {
    function createUpdater(routeFn: typeof router.push) {
      return function updater(newLocation: PartialLocationWithHash) {
        location.current = newLocation;
        // Debounce router calls to avoid user-visible changes to the browser URL.
        if (timeoutId.current != null) {
          clearTimeout(timeoutId.current);
        }
        timeoutId.current = setTimeout(() => {
          timeoutId.current = undefined;
          void routeFn(
            { pathname: router.pathname, ...newLocation },
            { pathname, ...newLocation },
            { shallow, scroll: false }
          );
        }, 0);
      };
    }

    return {
      push: createUpdater(router.push),
      replace: createUpdater(router.replace),
      get location() {
        return location.current;
      },
    };
  }, [pathname, router, shallow]);

  return children(adapter);
}

function getLocation(asPath: string, isReady: boolean): PartialLocationWithHash {
  if (typeof window !== "undefined") {
    // For SSG, no query parameters are available on the server side,
    // since they can't be known at build time. Therefore to avoid
    // markup mismatches, we need a two-part render in this case that
    // patches the client with the updated query parameters lazily.
    // Note that for SSR `router.isReady` will be `true` immediately
    // and therefore there's no two-part render in this case.
    if (isReady) {
      return window.location;
    }
    return { search: "" };
  } else {
    // On the server side we only need a subset of the available
    // properties of `Location`. The other ones are only necessary
    // for interactive features on the client.
    return { search: asPath.replace(pathnameRegex, "") };
  }
}

export default React.memo(NextQueryParamAdapter);
```

**Comment by amannn** [comment] 2022-10-20 12:53
Hi @trevorr and thanks for opening this issue, including your proposed fix!

I currently don't have the time to review this in detail, but if you'd like to open a PR along with a regression test, that would be really helpful! I'll try to find time to review it timely and cut a patch release.

**Comment by natterstefan** [comment] 2023-03-09 13:35
Hi @trevorr,

have you tried

> `{ options: { enableBatching: true}}` is added to the `QueryParamProvider`

as mentioned in this related issue https://github.com/pbeshai/use-query-params/issues/233?

**Comment by hallucinogenizer** [comment] 2024-01-10 07:08
I created a [codesandbox](https://codesandbox.io/p/devbox/use-query-params-local-storage-overwrite-issue-nextjs-t96rrm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clr7elo4d00083b6n80ltsa3u%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clr7elo4d00023b6nyb3gfs1n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clr7elo4d00053b6n9kg9a58i%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clr7elo4d00073b6nkqu5vjkp%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clr7elo4d00023b6nyb3gfs1n%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7elo4d00013b6n9jig34bl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clr7elo4d00023b6nyb3gfs1n%2522%252C%2522activeTabId%2522%253A%2522clr7elo4d00013b6n9jig34bl%2522%257D%252C%2522clr7elo4d00073b6nkqu5vjkp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7elo4d00063b6neo0ckqbf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%253Fparam2%253D3%2522%257D%255D%252C%2522id%2522%253A%2522clr7elo4d00073b6nkqu5vjkp%2522%252C%2522activeTabId%2522%253A%2522clr7elo4d00063b6neo0ckqbf%2522%257D%252C%2522clr7elo4d00053b6n9kg9a58i%2522%253A%257B%2522id%2522%253A%2522clr7elo4d00053b6n9kg9a58i%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clr7elo4d00033b6nwmc6kins%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clr7elo4d00033b6nwmc6kins%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) for this issue.


## What the issue is and how to reproduce it in the sandbox
- In the sandbox, I have two buttons, each incrementing the value of one query param in the URL. We have 2 query params therefore.
- When you click `Button 1`, it does 2 things:
    1. It increments the value of `param1` in the URL
    2. It increments the value of `param1` in localStorage
- Now click on `Button 2` and increment the value of `param2` in both URL as well as localStorage. Make sure it has a different value than `param1`.
- Now erase the params from the URL and re-visit the page (without any URL params).
- Since the params still exist in `localStorage`, they need to be restored from `localStorage`. For this, we have a `useEffect` that gets the values of both params from `localStorage` and sets them in URL.
- The problem is that even though both params exist in `localStorage`, only one is set in the URL (usually the second one). The second setParam call overwrites the first one.

**Comment by amannn** [comment] 2024-01-10 07:40
Thanks for leaving a note here @hallucinogenizer! I'll close this issue then.

**Closed by amannn** 2024-01-10 07:40 UTC
Labels: bug
